spring:
  profiles:
    active:
      - dev

# dev
spring:
  profiles: dev
  application:
    name: springcloud-study-dev

# test
spring:
  profiles: test
  application:
    name: springcloud-study-test

# 必须保存为UTF-8编码
