spring:
  profiles:
    active:
      - dev
---
spring:
  profiles: dev
info:
  name: shu
  age: 800
  gender: male
  
---
spring:
  profiles: test
info:
  name: Jane
  age: 30
  gender: female
# 必须保存为UTF-8编码
